layout: sidebar
style: light

plugins:
    - jekyll-octicons
    - jekyll-github-metadata
    - jemoji

permalink: /:year/:month/:day/:title/

defaults:
    - scope:
          path: '' # an empty string here means all files in the project
          type: 'posts'
      values:
          layout: 'post'
email: 'anubhav.srivastava00@gmail.com'
projects:
    sort_by: stars
    # sort_by options:
    #   - pushed
    #   - stars
    limit: 30
    exclude:
        forks: true
        projects:
            - awesome-chess

social_media:
    # behance: your_username
    # dribbble: your_username
    facebook: theanubhav
    # hackerrank: your_username
    # instagram: your_username
    # keybase: your_username
    linkedin: theanubhav
    medium: onlyanubhav
    stackoverflow: 2846906
    # telegram: your_username
    twitter: onlyanubhav
    # unsplash: your_username
    # vk: your_username
    website: https://theanubhav.com
    # youtube: your_username

topics:
    - name: JavaScript
      image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png

    - name: React
      image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/react/react.png

    - name: HTML/CSS
      image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/html/html.png

google_analytics: UA-45109327-3
